export const json = {
  data: [
    {
      cash: {position: 'headerPost'},
      data: null,
      userId: 'yeejun',
      userFriends: [],
      nickname: '뿡뿡이',
      userImage: [],
      content: {
        content:
          '캐쉬 결제해서 항상 맨 위에 고정되는 포스트를 날렸음. 하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하하',
        image: [],
      },
      firstContentImage: [],
      likePeople: [], // 유저들 id 들어감
      dislikePeople: [],
    },
    {
      cash: {position: 'bodyPost'},
      data: null,
      userId: 'yeejun2',
      userFriends: [],
      nickname: '염소',
      userImage: [],
      content: {content: '페이크데이타', image: []},
      firstContentImage: [],
      likePeople: [],
      dislikePeople: [],
    },
    {
      cash: {position: 'bodyPost'},
      data: null,
      userId: 'yeejun3',
      userFriends: [],
      nickname: '호랑이형님',
      userImage: [],
      content: {content: '바디포스트2 보냈음', image: []},
      firstContentImage: [],
      likePeople: [],
      dislikePeople: [],
    },
    {
      cash: {position: 'bodyPost'},
      data: null,
      userId: 'yeejun4',
      userFriends: [],
      nickname: '야채맨',
      userImage: [],
      content: {content: '음 바디포스트3 보냄', image: []},
      firstContentImage: [],
      likePeople: [],
      dislikePeople: [],
    },
    {
      cash: {position: 'bodyPost'},
      data: null,
      userId: 'yeejun5',
      userFriends: [],
      nickname: '상추맨',
      userImage: [],
      content: {content: '호호 메세지', image: []},
      firstContentImage: [],
      likePeople: [],
      dislikePeople: [],
    },
    {
      cash: {position: 'bodyPost'},
      data: null,
      userId: 'yeejun7',
      userFriends: [],
      nickname: '파조래기',
      userImage: [],
      content: {content: '야아아아아아 메세지', image: []},
      firstContentImage: [],
      likePeople: [],
      dislikePeople: [],
    },
    {
      cash: {position: 'bodyPost'},
      data: null,
      userId: 'yeejun8',
      userFriends: [],
      nickname: '캬캬맨',
      userImage: [],
      content: {content: '가짜 데이터임', image: []},
      firstContentImage: [],
      likePeople: [],
      dislikePeople: [],
    },
    {
      cash: {position: 'bodyPost'},
      data: null,
      userId: 'yeejun6',
      userFriends: [],
      nickname: '김치맨',
      userImage: [],
      content: {content: '마지막 메세지', image: []},
      firstContentImage: [],
      likePeople: [],
      dislikePeople: [],
    },
  ],
};
