export const json = {
  data: [
    {
      id: 1,
      alert: 'like',
      category: 'post',
      userId: 'yeejun2',
      userImage: [],
      nickname: '야채맨',
      time: '2019-12-06 14:02',
    },
    {
      id: 2,
      alert: 'like',
      category: 'profile',
      userId: 'yeejun3',
      userImage: [],
      nickname: '황소맨',
      time: '2019-12-06 14:22',
    },
    {
      id: 3,
      alert: 'dislike',
      category: 'post',
      userId: 'yeejun4',
      userImage: [],
      nickname: '얌얌얌',
      time: '2019-12-06 14:22',
    },
    {
      id: 4,
      alert: 'addFriend',
      category: 'profile',
      userId: 'yeejun4',
      userImage: [],
      nickname: '얌얌얌',
      time: '2019-12-06 14:32',
    },
    {
      id: 5,
      alert: 'reply',
      category: 'post',
      userId: 'yeejun4',
      userImage: [],
      nickname: '얌얌얌',
      time: '2019-12-06 14:42',
    },
    {
      id: 6,
      alert: 'reReply',
      category: 'post',
      userId: 'yeejun3',
      userImage: [],
      nickname: '황소맨',
      time: '2019-12-06 14:52',
    },
  ],
};
